parameters:
    ibexa.site_access.config.<scope>.image_asset_view_defaults:
        full:
            commons:
                template: '@@ibexadesign/commons_asset_view.html.twig'
                match:
                    SourceBasedViewMatcher: commons
            default:
                template: '@@ibexadesign/ui/field_type/image_asset_view.html.twig'
                match: []
