parameters:
    ibexa.content_view.image_embed_content_types_identifiers: [image, photo, banner]
    ibexa.default_view_templates.content.embed_image: '@ibexadesign/content/view/embed/image.html.twig'
