site_name: eZ Platform Developer Documentation
repo_url: https://github.com/ezsystems/developer-documentation
copyright: "Copyright 1999-2019 eZ Systems AS and others"
pages:
    - 'Documentation': 'index.md'
    - Getting started:
        - 'Quickstart': 'getting_started/quickstart.md'
        - 'Requirements': 'getting_started/requirements.md'
        - 'Install eZ Platform': 'getting_started/install_ez_platform.md'
        - 'Install eZ Enterprise': 'getting_started/install_ez_enterprise.md'
        - 'First steps': 'getting_started/first_steps.md'
        - 'Bundles starter pack': 'getting_started/bundles_starter_pack.md'
        - 'Troubleshooting': 'getting_started/troubleshooting.md'
    - Tutorials:
        - eZ Platform beginner:
            - 'eZ Platform beginner tutorial': 'tutorials/platform_beginner/building_a_bicycle_route_tracker_in_ez_platform.md'
            - '1. Get ready': 'tutorials/platform_beginner/1_get_ready.md'
            - '2. Create the content model': 'tutorials/platform_beginner/2_create_the_content_model.md'
            - '3. Customize the front page': 'tutorials/platform_beginner/3_customize_the_front_page.md'
            - '4. Display a single content item': 'tutorials/platform_beginner/4_display_single_content_item.md'
            - '5. Display a list of content items': 'tutorials/platform_beginner/5_display_a_list_of_content_items.md'
            - '6. Improve configuration': 'tutorials/platform_beginner/6_improve_configuration.md'
            - '7. Embed content': 'tutorials/platform_beginner/7_embed_content.md'
            - '8. Enable account registration': 'tutorials/platform_beginner/8_enable_account_registration.md'
        - eZ Enterprise beginner:
            - 'eZ Enterprise beginner tutorial': 'tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md'
            - '1. Get a starter website': 'tutorials/enterprise_beginner/1_get_a_starter_website.md'
            - '2. Prepare the Landing Page': 'tutorials/enterprise_beginner/2_prepare_the_landing_page.md'
            - '3. Use existing blocks': 'tutorials/enterprise_beginner/3_use_existing_blocks.md'
            - '4. Create a custom block': 'tutorials/enterprise_beginner/4_create_a_custom_block.md'
            - '5. Create a newsletter form': 'tutorials/enterprise_beginner/5_create_newsletter_form.md'
        - Create a Field Type:
            - 'Create a Tweet Field Type': 'tutorials/field_type/creating_a_tweet_field_type.md'
            - '1. Create the bundle': 'tutorials/field_type/1_create_the_bundle.md'
            - '2. Implement the Tweet&#92Value Class': 'tutorials/field_type/2_implement_the_tweet_value_class.md'
            - '3. Implement the Tweet&#92Type Class': 'tutorials/field_type/3_implement_the_tweet_type_class.md'
            - '4. Register the Field Type as a service': 'tutorials/field_type/4_register_the_field_type_as_a_service.md'
            - '5. Implement the legacy storage engine': 'tutorials/field_type/5_implement_the_legacy_storage_engine_converter.md'
            - '6. Introduce a template': 'tutorials/field_type/6_introduce_a_template.md'
            - '7. Allow adding and editing the Field in Back Office': 'tutorials/field_type/7_allow_adding_and_editing_the_field_in_back_office.md'
            - '8. Add a validation': 'tutorials/field_type/8_add_a_validation.md'
        - Extending Admin UI:
            - 'Extending Admin UI': 'tutorials/extending_admin_ui/extending_admin_ui.md'
            - '1. Creating a Dashboard tab': 'tutorials/extending_admin_ui/1_creating_a_dashboard_tab.md'
            - '2. Creating a content list': 'tutorials/extending_admin_ui/2_creating_a_content_list.md'
            - '3. Filtering the content list': 'tutorials/extending_admin_ui/3_filtering_the_content_list.md'
            - '4. Creating a custom tag': 'tutorials/extending_admin_ui/4_adding_a_custom_tag.md'
    - API:
        - REST API guide:
            - 'REST API guide': 'api/rest_api_guide.md'
            - 'REST API usage': 'api/general_rest_usage.md'
            - 'Extending the REST API': 'api/extending_the_rest_api.md'
            - 'REST API reference': 'api/rest_api_reference.md'
        - Public PHP API:
            - 'Public PHP API': 'api/public_php_api.md'
            - 'Browsing Content': 'api/public_php_api_browsing.md'
            - 'Content search': 'api/public_php_api_search.md'
            - 'Creating Content': 'api/public_php_api_creating_content.md'
            - 'Managing Content': 'api/public_php_api_managing_content.md'
            - 'Managing Repository': 'api/public_php_api_managing_repository.md'
        - Field Type:
            - 'Field Type API': 'api/field_type_api.md'
            - 'Type and Value': 'api/field_type_type_and_value.md'
            - 'Form and template': 'api/field_type_form_and_template.md'
            - 'Storage': 'api/field_type_storage.md'
            - 'Validation': 'api/field_type_validation.md'
            - 'Searching': 'api/field_type_search.md'
            - 'Reference': 'api/field_type_reference.md'
        - GraphQL:
            - 'GraphQL': 'api/graphql.md'
            - 'GraphQL queries': 'api/graphql_queries.md'
            - 'GraphQL operations': 'api/graphql_operations.md'
            - 'GraphQL customization': 'api/graphql_customization.md'
    - Guide:
        - 'Architecture': 'guide/architecture.md'
        - 'Bundles': 'guide/bundles.md'
        - Configuration:
            - 'Configuration': 'guide/configuration.md'
            - 'Dynamic config': 'guide/config_dynamic.md'
            - 'Back Office config': 'guide/config_back_office.md'
            - 'Repository config': 'guide/config_repository.md'
        - 'Admin management': 'guide/admin_panel.md'
        - 'Content model': 'guide/content_model.md'
        - Content rendering:
            - 'Content rendering': 'guide/content_rendering.md'
            - 'Controllers': 'guide/controllers.md'
            - 'Templates': 'guide/templates.md'
            - 'Design engine': 'guide/design_engine.md'
            - 'Page rendering': 'guide/page_rendering.md'
            - 'Twig functions reference': 'guide/twig_functions_reference.md'
        - Content management:
            - 'Content management': 'guide/content_management.md'
            - 'Images': 'guide/images.md'
            - 'File management': 'guide/file_management.md'
            - 'URL management': 'guide/url_management.md'
            - 'User-generated content': 'guide/user_generated_content.md'
            - 'Editorial workflow': 'guide/workflow.md'
        - Permissions:
            - 'Permissions': 'guide/permissions.md'
            - 'Limitations': 'guide/limitations.md'
            - 'Limitation reference': 'guide/limitation_reference.md'
            - 'User management': 'guide/user_management.md'
            - 'Custom Policies': 'guide/custom_policies.md'
        - 'Backup': 'guide/backup.md'
        - Search:
            - 'Search': 'guide/search.md'
            - 'Solr search engine': 'guide/solr.md'
            - 'Other search engines': 'guide/search_engines.md'
        - Multisite:
            - 'Multisite': 'guide/multisite.md'
            - 'SiteAccess': 'guide/siteaccess.md'
            - 'Multi-language SiteAccesses': 'guide/multi_language_siteaccesses.md'
        - Languages:
            - 'Languages': 'guide/internationalization.md'
            - 'Back Office translations': 'guide/back_office_translations.md'
        - Repository:
            - 'Repository': 'guide/repository.md'
            - 'Databases': 'guide/databases.md'
        - Cache:
            - 'HTTP cache': 'guide/http_cache.md'
            - 'Persistence cache': 'guide/persistence_cache.md'
        - Clustering:
            - 'Clustering': 'guide/clustering.md'
            - 'AWS S3 clustering': 'guide/clustering_aws_s3.md'
        - DevOps:
            - 'DevOps': 'guide/devops.md'
            - 'Performance': 'guide/performance.md'
            - 'Environments': 'guide/environments.md'
            - 'Sessions': 'guide/sessions.md'
        - Security:
            - 'Development Security': 'guide/security.md'
            - 'Reporting Issues': 'guide/reporting_issues.md'
        - Extending eZ Platform:
            - 'Extending eZ Platform': 'guide/extending_ez_platform.md'
            - 'Extending modules': 'guide/extending_modules.md'
            - 'Extending the Online Editor': 'guide/extending_online_editor.md'
            - 'Extending Form Builder': 'guide/extending_form_builder.md'
            - 'Creating custom Page blocks': 'guide/extending_page.md'
            - 'Creating custom richtext blocks': 'guide/richtext_block.md'
            - 'Creating custom drop-downs': 'guide/creating_custom_dropdowns.md'
            - 'Creating drag and drop interface': 'guide/drag_and_drop.md'
        - 'Service container': 'guide/service_container.md'
        - 'Recommendation': 'guide/personalization.md'
    - Cookbook:
        - 'Accept header-based REST API response': 'cookbook/creating_custom_rest_api_response.md'
        - 'Binary attachments via REST API': 'cookbook/creating_content_with_binary_attachments_via_rest_api.md'
        - 'Cross-origin HTTP requests': 'cookbook/making_cross_origin_http_requests.md'
        - 'Customizing email notifications': 'cookbook/customizing_form_builder_email_notifications.md'
        - 'Displaying Content children': 'cookbook/displaying_children_of_a_content_item.md'
        - 'Installing on macOS or Windows': 'cookbook/installing-on-mac-os-and-windows.md'
        - 'Multiple user providers': 'cookbook/authenticating_a_user_with_multiple_user_providers.md'
        - 'Notifications': 'cookbook/sending_notifications.md'
        - 'Retrieving root Location': 'cookbook/retrieving_root_location.md'
        - 'RouteReference': 'cookbook/using_routereference.md'
        - 'SiteAccess-aware bundle configuration': 'cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md'
        - 'Using simple templates': 'cookbook/displaying_content_with_simple_templates.md'
    - Resources and community:
        - 'Resources': 'community_resources/resources.md'
        - 'Release process and roadmap': 'community_resources/release_process.md'
        - 'Support and Maintenance FAQ': 'community_resources/support_maintenance_faq.md'
        - Contributing:
            - 'How to contribute': 'community_resources/contributing.md'
            - 'Report and follow issues': 'community_resources/report_follow_issues.md'
            - 'Development guidelines': 'community_resources/development_guidelines.md'
            - 'Contribute code': 'community_resources/code.md'
            - 'Contribute translations': 'community_resources/translations.md'
            - 'Contribute documentation': 'community_resources/documentation.md'
        - UI Guidelines:
            - 'Introduction': 'guidelines/Introduction.md'
            - Components:
                - 'Buttons': 'guidelines/components/buttons.md'
                - 'Form components': 'guidelines/components/form_components.md'
                - 'Modals': 'guidelines/components/modals.md'
                - 'Pagination': 'guidelines/components/pagination.md'
                - 'Switchers': 'guidelines/components/switchers.md'
                - 'Tables': 'guidelines/components/tables.md'
                - 'Tabs': 'guidelines/components/tabs.md'
            - Resources:
                - 'Typography': 'guidelines/resources/typography.md'
                - 'Colors': 'guidelines/resources/colors.md'
                - 'Icons': 'guidelines/resources/icons.md'
            - Design Principles:
                - 'Philosophy': 'guidelines/design_principles/Philosophy.md'
                - 'Accessibility': 'guidelines/design_principles/Accessibility.md'
    - Migrating to eZ Platform:
        - 'Migrating from eZ Publish Platform': 'migrating/migrating_from_ez_publish_platform.md'
        - 'Migrating from eZ Publish': 'migrating/migrating_from_ez_publish.md'
        - 'Common issues': 'migrating/common_issues.md'
    - Updating eZ Platform:
        - 'Updating eZ Platform': 'updating/updating_ez_platform.md'
        - '1. Check out a tagged version': 'updating/1_check_out_version.md'
        - '2. Merge composer.json': 'updating/2_merge_composer.md'
        - '3. Update the app': 'updating/3_update_app.md'
        - '4. Update database':
          - 'Update database': 'updating/4_update_database.md'
          - 'Updating from <1.7': 'updating/4_update_1.7.md'
          - 'Updating from <1.13': 'updating/4_update_1.13.md'
          - 'Updating from <2.2': 'updating/4_update_2.2.md'
          - 'Updating from <2.3': 'updating/4_update_2.3.md'
          - 'Updating from <2.4': 'updating/4_update_2.4.md'
          - 'Updating from <2.5': 'updating/4_update_2.5.md'
        - '5. Platform.sh changes': 'updating/5_platform_sh_changes.md'
        - '6. Dump assets': 'updating/6_dump_assets.md'
        - '7. Commit, test and merge': 'updating/7_commit_test_merge.md'
    - Releases:
        - 'eZ Platform v3.0 deprecations and BC breaks': 'releases/ez_platform_v3.0_deprecations.md'
        - 'eZ Platform v3.0 project update': 'releases/ez_platform_v3.0_project_update.md'
        - 'eZ Platform v2.5 LTS': 'releases/ez_platform_v2.5.md'
        - 'eZ Platform v2.4': 'releases/ez_platform_v2.4.md'
        - 'eZ Platform v2.3': 'releases/ez_platform_v2.3.md'
        - 'eZ Platform v2.2.0': 'releases/ez_platform_v2.2.0.md'
        - 'eZ Platform v2.1.0': 'releases/ez_platform_v2.1.0.md'
        - 'eZ Platform v2.0.0': 'releases/ez_platform_v2.0.0.md'
        - 'eZ Platform v1.13.0 LTS': 'releases/ez_platform_v1.13.0_lts.md'
        - 'eZ Platform v1.12.0': 'releases/ez_platform_v1.12.0.md'
        - 'eZ Platform v1.11.0': 'releases/ez_platform_v1.11.0.md'
        - 'eZ Platform v1.10.0': 'releases/ez_platform_v1.10.0.md'
        - 'eZ Platform v1.9.0': 'releases/ez_platform_v1.9.0.md'
        - 'eZ Platform v1.8.0': 'releases/ez_platform_v1.8.0.md'
        - 'eZ Platform v1.7.0 LTS': 'releases/ez_platform_v1.7.0_lts.md'
        - 'eZ Platform v1.6.0': 'releases/ez_platform_and_ez_enterprise_v1.6.0.md'
        - eZ Enterprise release notes:
            - 'eZ Enterprise v1.5.0': 'releases/ez_enterprise_v1.5.0_release_notes.md'
            - 'eZ Enterprise v1.4.0': 'releases/ez_enterprise_v1.4_release_notes.md'
            - 'eZ Studio 2016.04': 'releases/ez_studio_2016.04_release_notes.md'
            - 'eZ Studio 16.02': 'releases/ez_studio_16.02_release_notes.md'
            - 'eZ Studio 15.12.1': 'releases/ez_studio_15.12.1_release_notes.md'
            - 'eZ Studio 15.12': 'releases/ez_studio_15.12_release_notes.md'
        - eZ Platform release notes:
            - 'eZ Platform v1.5.1': 'releases/ez_platform_1.5.1_release_notes.md'
            - 'eZ Platform v1.5.0': 'releases/ez_platform_v1.5.0_release_notes.md'
            - 'eZ Platform v1.4.2': 'releases/ez_platform_1.4.2_release_notes.md'
            - 'eZ Platform v1.4.0': 'releases/ez_platform_v1.4.0_release_notes.md'
            - 'eZ Platform 2016.04': 'releases/ez_platform_2016.04_release_notes.md'
            - 'eZ Platform 16.02': 'releases/ez_platform_16.02_release_notes.md'
            - 'eZ Platform 15.12.1': 'releases/ez_platform_15.12.1_release_notes.md'
            - 'eZ Platform 15.12': 'releases/ez_platform_15.12_release_notes.md'
            - 'Earlier releases': 'releases/earlier_releases.md'
    - 'References': 'references.md'
theme:
  name: null
  custom_dir: 'material'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
      primary: 'blue grey'
      accent: 'deep orange'

  font: false
  logo: 'images/eZ-Brandmark.png'
  feature:
      tabs: false
  search_index_only: false

theme_dir: material

extra:
  version_warning:
    latest: ['2.5']
    previous_lts: ['1.7','1.13']
    lts: ['2.5']
    ft: ['2.2', '2.3','2.4']
    dev: ['master']
  append_bootstrap:
    - '/guidelines/'
    - '/index.md'
  related_docs:
    - title: 'eZ Platform Developer Documentation'
      url: '/'
    - title: 'eZ Platform User Documentation'
      url: '/projects/userguide'
    - title: 'eZ Personalization Documentation'
      url: '/projects/ezpersonalization'
    - title: 'eZ Commerce'
      url: 'https://doc.ez.no/commerce'

extra_css:
  - fonts/MavenPro.css
  - css/custom.css
  - css/docs.switcher.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/custom.js
  - js/docs.switcher.js
  - js/ez-guidelines-switchers.js
  - js/ez-guidelines-modals.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - ez_code_example
