site_name: Developer Documentation
repo_url: https://github.com/ezsystems/developer-documentation
site_url: https://doc.ibexa.co/en/latest/
copyright: "Copyright 1999-2021 Ibexa AS and others"
nav:
    - 'eZ Platform Developer Documentation': 'index.md'
    - Getting started:
        - 'Quickstart': 'getting_started/quickstart.md'
        - 'Requirements': 'getting_started/requirements.md'
        - 'Install eZ Platform': 'getting_started/install_ez_platform.md'
        - 'Install eZ Enterprise': 'getting_started/install_ez_enterprise.md'
        - 'First steps': 'getting_started/first_steps.md'
        - 'Bundles starter pack': 'getting_started/bundles_starter_pack.md'
        - 'Troubleshooting': 'getting_started/troubleshooting.md'
    - Tutorials:
        - eZ Platform beginner:
            - 'eZ Platform beginner tutorial': 'tutorials/platform_beginner/building_a_bicycle_route_tracker_in_ez_platform.md'
            - '1. Get ready': 'tutorials/platform_beginner/1_get_ready.md'
            - '2. Create the content model': 'tutorials/platform_beginner/2_create_the_content_model.md'
            - '3. Customize the front page': 'tutorials/platform_beginner/3_customize_the_front_page.md'
            - '4. Display a list of content items': 'tutorials/platform_beginner/4_display_a_list_of_content_items.md'
            - '5. Improve configuration': 'tutorials/platform_beginner/5_improve_configuration.md'
            - '6. Embed content': 'tutorials/platform_beginner/6_embed_content.md'
            - '7. Enable account registration': 'tutorials/platform_beginner/7_enable_account_registration.md'
        - eZ Enterprise beginner:
            - 'eZ Enterprise beginner tutorial': 'tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md'
            - '1. Get a starter website': 'tutorials/enterprise_beginner/1_get_a_starter_website.md'
            - '2. Prepare the Landing Page': 'tutorials/enterprise_beginner/2_prepare_the_landing_page.md'
            - '3. Use existing blocks': 'tutorials/enterprise_beginner/3_use_existing_blocks.md'
            - '4. Create a custom block': 'tutorials/enterprise_beginner/4_create_a_custom_block.md'
        - Create a Field Type:
            - 'Create a Tweet Field Type': 'tutorials/field_type/creating_a_tweet_field_type.md'
            - '1. Create the bundle': 'tutorials/field_type/1_create_the_bundle.md'
            - '2. Implement the Tweet&#92Value Class': 'tutorials/field_type/2_implement_the_tweet_value_class.md'
            - '3. Implement the Tweet&#92Type Class': 'tutorials/field_type/3_implement_the_tweet_type_class.md'
            - '4. Register the Field Type as a service': 'tutorials/field_type/4_register_the_field_type_as_a_service.md'
            - '5. Implement the legacy storage engine': 'tutorials/field_type/5_implement_the_legacy_storage_engine_converter.md'
            - '6. Introduce a template': 'tutorials/field_type/6_introduce_a_template.md'
            - '7. Add content and edit views': 'tutorials/field_type/7_add_content_and_edit_views.md'
            - '8. Add a validation': 'tutorials/field_type/8_add_a_validation.md'
    - API:
        - REST API guide:
            - 'REST API guide': 'api/rest_api_guide.md'
            - 'REST API usage': 'api/general_rest_usage.md'
            - 'Extending the REST API': 'api/extending_the_rest_api.md'
            - 'JavaScript client': 'api/js_client.md'
            - 'REST API reference': 'api/rest_api_reference/rest_api_reference.html'
            - 'Accept header-based REST API response': 'api/creating_custom_rest_api_response.md'
            - 'Binary attachments via REST API': 'api/creating_content_with_binary_attachments_via_rest_api.md'
            - 'Cross-origin HTTP requests': 'api/making_cross_origin_http_requests.md'
        - Public PHP API:
            - 'Public PHP API': 'api/public_php_api.md'
            - 'Browsing Content': 'api/public_php_api_browsing.md'
            - 'Content search': 'api/public_php_api_search.md'
            - 'Creating Content': 'api/public_php_api_creating_content.md'
            - 'Managing Content': 'api/public_php_api_managing_content.md'
            - 'Managing Repository': 'api/public_php_api_managing_repository.md'
            - 'URL Service': 'api/public_php_api_url_service.md'
            - URL reference:
                - 'Id Sort Clause': 'api/url_reference/id_sort_clause.md'
                - 'Url Sort Clause': 'api/url_reference/url_sort_clause.md'
                - 'MatchAll Criterion': 'api/url_reference/matchall_criterion.md'
                - 'MatchNone Criterion': 'api/url_reference/matchnone_criterion.md'
                - 'Pattern Criterion': 'api/url_reference/pattern_criterion.md'
                - 'SectionId Criterion': 'api/url_reference/sectionid_criterion.md'
                - 'SectionIdentifier Criterion': 'api/url_reference/sectionidentifier_criterion.md'
                - 'Validity Criterion': 'api/url_reference/validity_criterion.md'
                - 'VisibleOnly Criterion': 'api/url_reference/visibleonly_criterion.md'
                - 'LogicalAnd Criterion': 'api/url_reference/logicaland_criterion.md'
                - 'LogicalNot Criterion': 'api/url_reference/logicalnot_criterion.md'
                - 'LogicalOr Criterion': 'api/url_reference/logicalor_criterion.md'
        - Field Type:
            - 'Field Type API': 'api/field_type_api.md'
            - 'Type and Value': 'api/field_type_type_and_value.md'
            - 'Form and template': 'api/field_type_form_and_template.md'
            - 'Storage': 'api/field_type_storage.md'
            - 'Validation': 'api/field_type_validation.md'
            - 'Searching': 'api/field_type_search.md'
            - 'Reference': 'api/field_type_reference.md'
    - Guide:
        - 'Architecture': 'guide/architecture.md'
        - 'Bundles': 'guide/bundles.md'
        - Configuration:
            - 'Configuration': 'guide/configuration.md'
            - 'Dynamic config': 'guide/config_dynamic.md'
            - 'Back Office config': 'guide/config_back_office.md'
            - 'Repository config': 'guide/config_repository.md'
        - 'Admin management': 'guide/admin_panel.md'
        - 'Content model': 'guide/content_model.md'
        - Content rendering:
            - 'Content rendering': 'guide/content_rendering.md'
            - 'Controllers': 'guide/controllers.md'
            - 'Templates': 'guide/templates.md'
            - 'Design engine': 'guide/design_engine.md'
            - 'Landing Page rendering': 'guide/landing_page_rendering.md'
            - 'Displaying Content children': 'guide/displaying_children_of_a_content_item.md'
            - 'Retrieving root Location': 'guide/retrieving_root_location.md'
            - 'Twig functions reference': 'guide/twig_functions_reference.md'
        - Content management:
            - 'Content management': 'guide/content_management.md'
            - 'Images': 'guide/images.md'
            - 'File management': 'guide/file_management.md'
            - 'RouteReference': 'guide/routereference.md'
            - 'URL management': 'guide/url_management.md'
            - 'User-generated content': 'guide/user_generated_content.md'
        - Permissions:
            - 'Permissions': 'guide/permissions.md'
            - 'Limitations': 'guide/limitations.md'
            - 'Limitation reference': 'guide/limitation_reference.md'
            - 'User management': 'guide/user_management.md'
            - 'Custom Policies': 'guide/custom_policies.md'
        - 'Backup': 'guide/backup.md'
        - Search:
            - 'Search': 'guide/search/search.md'
            - 'Search Criteria reference': 'guide/search/search_criteria_reference.md'
            - Search Criteria reference:
                - 'Ancestor': 'guide/search/criteria_reference/ancestor_criterion.md'
                - 'ContentId': 'guide/search/criteria_reference/contentid_criterion.md'
                - 'ContentTypeGroupId': 'guide/search/criteria_reference/contenttypegroupid_criterion.md'
                - 'ContentTypeId': 'guide/search/criteria_reference/contenttypeid_criterion.md'
                - 'ContentTypeIdentifier': 'guide/search/criteria_reference/contenttypeidentifier_criterion.md'
                - 'DateMetadata': 'guide/search/criteria_reference/datemetadata_criterion.md'
                - 'Depth': 'guide/search/criteria_reference/depth_criterion.md'
                - 'Field': 'guide/search/criteria_reference/field_criterion.md'
                - 'FieldRelation': 'guide/search/criteria_reference/fieldrelation_criterion.md'
                - 'FullText': 'guide/search/criteria_reference/fulltext_criterion.md'
                - 'IsMainLocation': 'guide/search/criteria_reference/ismainlocation_criterion.md'
                - 'LanguageCode': 'guide/search/criteria_reference/languagecode_criterion.md'
                - 'LocationId': 'guide/search/criteria_reference/locationid_criterion.md'
                - 'LocationRemoteId': 'guide/search/criteria_reference/locationremoteid_criterion.md'
                - 'MapLocationDistance': 'guide/search/criteria_reference/maplocationdistance_criterion.md'
                - 'MatchAll': 'guide/search/criteria_reference/matchall_criterion.md'
                - 'MatchNone': 'guide/search/criteria_reference/matchnone_criterion.md'
                - 'ObjectStateId': 'guide/search/criteria_reference/objectstateid_criterion.md'
                - 'ParentLocationId': 'guide/search/criteria_reference/parentlocationid_criterion.md'
                - 'Priority': 'guide/search/criteria_reference/priority_criterion.md'
                - 'RemoteId': 'guide/search/criteria_reference/remoteid_criterion.md'
                - 'SectionId': 'guide/search/criteria_reference/sectionid_criterion.md'
                - 'Subtree': 'guide/search/criteria_reference/subtree_criterion.md'
                - 'UserMetadata': 'guide/search/criteria_reference/usermetadata_criterion.md'
                - 'Visibility': 'guide/search/criteria_reference/visibility_criterion.md'
                - 'LogicalAnd Criterion': 'guide/search/criteria_reference/logicaland_criterion.md'
                - 'LogicalNot Criterion': 'guide/search/criteria_reference/logicalnot_criterion.md'
                - 'LogicalOr Criterion': 'guide/search/criteria_reference/logicalor_criterion.md'
            - 'Sort Clause reference': 'guide/search/sort_clause_reference.md'
            - Sort Clause Reference:
                - 'ContentId': 'guide/search/sort_clause_reference/contentid_sort_clause.md'
                - 'ContentName': 'guide/search/sort_clause_reference/contentname_sort_clause.md'
                - 'DateModified': 'guide/search/sort_clause_reference/datemodified_sort_clause.md'
                - 'DatePublished': 'guide/search/sort_clause_reference/datepublished_sort_clause.md'
                - 'Depth': 'guide/search/sort_clause_reference/depth_sort_clause.md'
                - 'Field': 'guide/search/sort_clause_reference/field_sort_clause.md'
                - 'Id': 'guide/search/sort_clause_reference/id_sort_clause.md'
                - 'IsMainLocation': 'guide/search/sort_clause_reference/ismainlocation_sort_clause.md'
                - 'MapLocationDistance': 'guide/search/sort_clause_reference/maplocationdistance_sort_clause.md'
                - 'Path': 'guide/search/sort_clause_reference/path_sort_clause.md'
                - 'Priority': 'guide/search/sort_clause_reference/priority_sort_clause.md'
                - 'SectionIdentifier': 'guide/search/sort_clause_reference/sectionidentifier_sort_clause.md'
                - 'SectionName': 'guide/search/sort_clause_reference/sectionname_sort_clause.md'
                - 'Visibility': 'guide/search/sort_clause_reference/visibility_sort_clause.md'
            - 'Solr search engine': 'guide/search/solr.md'
            - 'Other search engines': 'guide/search/search_engines.md'
        - Multisite:
            - 'Multisite': 'guide/multisite.md'
            - 'SiteAccess': 'guide/siteaccess.md'
            - 'SiteAccess Matching': 'guide/siteaccess_matching.md'
            - 'Multi-language SiteAccesses': 'guide/multi_language_siteaccesses.md'
        - Languages:
            - 'Languages': 'guide/internationalization.md'
            - 'Back Office translations': 'guide/back_office_translations.md'
        - Repository:
            - 'Repository': 'guide/repository.md'
            - 'SignalSlots': 'guide/signalslots.md'
            - 'Signals reference': 'guide/signals_reference.md'
        - Cache:
            - 'HTTP cache': 'guide/http_cache.md'
            - 'Persistence cache': 'guide/persistence_cache.md'
        - Clustering:
            - 'Clustering': 'guide/clustering.md'
            - 'AWS S3 clustering': 'guide/clustering_aws_s3.md'
        - DevOps:
            - 'DevOps': 'guide/devops.md'
            - 'Performance': 'guide/performance.md'
            - 'Environments': 'guide/environments.md'
            - 'Sessions': 'guide/sessions.md'
        - Security:
            - 'Development Security': 'guide/security.md'
            - 'Security checklist': 'guide/security_checklist.md'
            - 'Reporting Issues': 'guide/reporting_issues.md'
        - 'Notifications': 'guide/custom_notifications_for_flex_workflow.md'
        - Extending eZ Platform:
            - 'Extending eZ Platform': 'guide/extending_ez_platform.md'
            - 'Extending the Dashboard': 'guide/dashboard.md'
            - 'Extending Form Builder' : 'guide/extending_form_builder.md'
            - 'Other extensibility': 'guide/other_extensibility.md'
        - 'Service container': 'guide/service_container.md'
        - 'Personalization': 'guide/personalization.md'
    - Resources and community:
        - 'Resources': 'community_resources/resources.md'
        - 'Release process and roadmap': 'community_resources/release_process.md'
        - Contributing:
            - 'Installing eZ Platform on macOS or Windows': 'community_resources/installing-on-mac-os-and-windows.md'
            - 'How to contribute': 'community_resources/contributing.md'
            - 'Report and follow issues': 'community_resources/report_follow_issues.md'
            - 'Development guidelines': 'community_resources/development_guidelines.md'
            - 'Contribute translations': 'community_resources/translations.md'
            - 'Contribute to documentation': 'community_resources/documentation.md'
    - Update and migration:
        - Updating Ibexa DXP:
            - 'Updating to v3.3': 'updating/updating_to_3.3.md'
            - 'Updating Ibexa DXP': 'updating/updating.md'
            - '1. Check out a version': 'updating/1_check_out_version.md'
            - '2. Resolve conflicts': 'updating/2_merge_composer.md'
            - '3. Update the app': 'updating/3_update_app.md'
            - '4. Upgrade the code':
                - '4. Upgrade the code': 'updating/4_upgrade_the_code.md'
                - '4.1. Upgrade templates': 'updating/4_1_upgrade_templates.md'
                - '4.2. Upgrade configuration': 'updating/4_2_upgrade_configuration.md'
                - '4.3. Upgrade Field Types': 'updating/4_3_upgrade_field_types.md'
                - '4.4. Upgrade Signal Slots': 'updating/4_4_upgrade_signal_slots.md'
                - '4.5. Upgrade Online Editor': 'updating/4_5_upgrade_online_editor.md'
                - '4.6. Upgrade workflow': 'updating/4_6_upgrade_workflow.md'
                - '4.7. Upgrade extended code': 'updating/4_7_upgrade_extensions.md'
                - '4.8. Upgrade REST': 'updating/4_8_upgrade_rest.md'
                - '4.9 Other code upgrades': 'updating/4_9_upgrade_other.md'
            - '5. Update the database':
                - 'Update database': 'updating/5_update_database.md'
                - 'Update database to v1.13': 'updating/5_update_1.13.md'
                - 'Update database to v2.2': 'updating/5_update_2.2.md'
                - 'Update database to v2.3': 'updating/5_update_2.3.md'
                - 'Update database to v2.4': 'updating/5_update_2.4.md'
                - 'Update database to v2.5': 'updating/5_update_2.5.md'
                - 'Update database to v3.0': 'updating/5_update_3.0.md'
                - 'Update database to v3.1': 'updating/5_update_3.1.md'
                - 'Update database to v3.2': 'updating/5_update_3.2.md'
            - '6. Finish the update': 'updating/6_finish_the_update.md'
        - Migrating to Ibexa DXP:
            - 'Migrating from eZ Publish Platform': 'migrating/migrating_from_ez_publish_platform.md'
            - 'Migrating from eZ Publish': 'migrating/migrating_from_ez_publish.md'
            - 'Legacy Bridge': 'migrating/legacy_bridge.md'
            - 'Common issues': 'migrating/common_issues.md'
    - Releases:
        - 'Ibexa DXP v3.3 LTS': 'releases/ibexa_dxp_v3.3.md'
        - 'Ibexa DXP v3.2': 'releases/ibexa_dxp_v3.2.md'
        - 'eZ Platform v3.1': 'releases/ez_platform_v3.1.md'
        - 'eZ Platform v3.0': 'releases/ez_platform_v3.0.md'
        - 'eZ Platform v3.0 deprecations and BC breaks': 'releases/ez_platform_v3.0_deprecations.md'
        - 'eZ Platform v2.5 LTS': 'releases/ez_platform_v2.5.md'
        - 'eZ Platform v2.4': 'releases/ez_platform_v2.4.md'
        - 'eZ Platform v2.3': 'releases/ez_platform_v2.3.md'
        - 'eZ Platform v2.2.0': 'releases/ez_platform_v2.2.0.md'
        - 'eZ Platform v2.1.0': 'releases/ez_platform_v2.1.0.md'
        - 'eZ Platform v2.0.0': 'releases/ez_platform_v2.0.0.md'
        - 'eZ Platform v1.13.0 LTS': 'releases/ez_platform_v1.13.0_lts.md'
        - 'eZ Platform v1.12.0': 'releases/ez_platform_v1.12.0.md'
        - 'eZ Platform v1.11.0': 'releases/ez_platform_v1.11.0.md'
        - 'eZ Platform v1.10.0': 'releases/ez_platform_v1.10.0.md'
        - 'eZ Platform v1.9.0': 'releases/ez_platform_v1.9.0.md'
        - 'eZ Platform v1.8.0': 'releases/ez_platform_v1.8.0.md'
        - 'eZ Platform v1.7.0 LTS': 'releases/ez_platform_v1.7.0_lts.md'
    - 'References': 'references.md'

theme:
    name: material
    custom_dir: 'theme'
    favicon: 'images/favicon.png'
    language: 'en'
    palette:
        primary: 'blue grey'
        accent: 'deep orange'
    logo: 'images/ibexa-dxp-logo.svg'

plugins:
    - search
    # - macros:
    #     j2_block_start_string: '[[%'
    #     j2_block_end_string: '%]]'
    #     j2_variable_start_string: '[[='
    #     j2_variable_end_string: '=]]'

extra:
  append_bootstrap:
    - '/guidelines/'
    - '/index.md'
  related_docs:
    - title: 'Developer Documentation'
      url: '/'
    - title: 'User Documentation'
      url: '/projects/userguide'

extra_css:
  - fonts/MavenPro.css
  - css/codehilite.css
  - css/switcher.css
  - css/custom.css
  - css/page-not-found.css
  - css/navigation.css
  - css/docs.switcher.css
  - css/jquery-ui.min.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/jquery-ui.min.js
  - js/custom.js
  - js/docs.switcher.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
