site_name: eZ Platform Developer Documentation
repo_url: https://github.com/ezsystems/developer-documentation
copyright: "Copyright 1999-2017 eZ Systems AS and others"
pages:
    - 'Documentation': 'index.md'
    - Getting started:
        - 'Get started with eZ Platform': 'getting_started/get_started_with_ez_platform.md'
        - 'Requirements and system configuration': 'getting_started/requirements_and_system_configuration.md'
        - Installation:
            - 'Install eZ Platform': 'getting_started/install_ez_platform.md'
            - 'Install using Composer': 'getting_started/install_using_composer.md'
            - 'Install manually': 'getting_started/install_manually.md'
            - 'Install using Docker': 'getting_started/install_using_docker.md'
            - 'Starting eZ Platform': 'getting_started/starting_ez_platform.md'
            - 'Set up directory permissions': 'getting_started/set_up_directory_permissions.md'
            - 'Troubleshooting': 'getting_started/troubleshooting.md'
        - Going deeper:
            - 'eZ Platform features': 'getting_started/ez_platform_features.md'
            - 'eZ Enterprise': 'getting_started/ez_enterprise.md'
            - 'About Composer': 'getting_started/about_composer.md'
    - Tutorials:
        - 'Tutorials': 'tutorials/tutorials.md'
        - eZ Platform Beginner tutorial:
            - 'Building a bicycle route tracker in eZ Platform': 'tutorials/platform_beginner/building_a_bicycle_route_tracker_in_ez_platform.md'
            - '1. Getting ready': 'tutorials/platform_beginner/1_getting_ready.md'
            - '2. Creating your content model': 'tutorials/platform_beginner/2_creating_your_content_model.md'
            - '3. Customizing the general layout': 'tutorials/platform_beginner/3_customizing_the_general_layout.md'
            - '4. Displaying content of a ride': 'tutorials/platform_beginner/4_displaying_content_of_a_ride.md'
            - '5. Displaying the list of rides on the homepage': 'tutorials/platform_beginner/5_displaying_the_list_of_rides_on_the_homepage.md'
            - '6. Enabling Account Registration': 'tutorials/platform_beginner/6_enabling_account_registration.md'
            - '7. Customize the User forms': 'tutorials/platform_beginner/7_customize_login_and_register_forms.md'
        - eZ Enterprise Beginner tutorial:
            - 'eZ Enterprise beginner tutorial - It&#39s a dog&#39s world!': 'tutorials/enterprise_beginner/ez_enterprise_beginner_tutorial_-_its_a_dogs_world.md'
            - '1. Getting your starter website': 'tutorials/enterprise_beginner/1_getting_your_starter_website.md'
            - '2. Preparing the Landing Page': 'tutorials/enterprise_beginner/2_preparing_the_landing_page.md'
            - '3. Using existing blocks': 'tutorials/enterprise_beginner/3_using_existing_blocks.md'
            - '4. Creating a custom block': 'tutorials/enterprise_beginner/4_creating_a_custom_block.md'
        - Field Type Creation Tutorial:
            - 'Creating a Tweet Field Type': 'tutorials/field_type/creating_a_tweet_field_type.md'
            - '1. Create the bundle': 'tutorials/field_type/1_create_the_bundle.md'
            - '2. Implement the Tweet&#92Value Class': 'tutorials/field_type/2_implement_the_tweet_value_class.md'
            - '3. Implement the Tweet&#92Type Class': 'tutorials/field_type/3_implement_the_tweet_type_class.md'
            - '4. Register the Field Type as a service': 'tutorials/field_type/4_register_the_field_type_as_a_service.md'
            - '5. Implement the legacy storage engine': 'tutorials/field_type/5_implement_the_legacy_storage_engine_converter.md'
            - '6. Introduce a template': 'tutorials/field_type/6_introduce_a_template.md'
            - '7. Add content and edit views': 'tutorials/field_type/7_add_content_and_edit_views.md'
            - '8. Add a validation': 'tutorials/field_type/8_add_a_validation.md'
        - Extending PlatformUI with new navigation:
            - 'Extending PlatformUI with new navigation': 'tutorials/extending_platformui/extending_platformui_with_new_navigation.md'
            - '1. Create the extension bundle': 'tutorials/extending_platformui/1_create_the_extension_bundle.md'
            - '2. Set up the configuration': 'tutorials/extending_platformui/2_set_up_the_configuration.md'
            - '3. Alter the JavaScript application routing': 'tutorials/extending_platformui/3_alter_the_javascript_application_routing.md'
            - '4. Define a view': 'tutorials/extending_platformui/4_define_a_view.md'
            - '5. Configure the navigation': 'tutorials/extending_platformui/5_configure_the_navigation.md'
            - '6. Build the content list': 'tutorials/extending_platformui/6_build_the_content_list.md'
            - '7. Paginate results': 'tutorials/extending_platformui/7_paginate_results.md'
            - '8. Filter by Content Type': 'tutorials/extending_platformui/8_filter_by_content_type.md'
            - 'Conclusion': 'tutorials/extending_platformui/conclusion.md'
    - API:
        - REST API guide:
            - 'REST API guide': 'api/rest_api_guide.md'
            - 'REST API usage': 'api/general_rest_usage.md'
            - 'Extending the REST API': 'api/extending_the_rest_api.md'
            - 'JavaScript client': 'api/js_client.md'
            - 'REST API reference': 'api/rest_api_reference.md'
        - Public PHP API:
            - 'Public PHP API': 'api/public_php_api.md'
            - 'Customization': 'api/public_php_api_customization.md'
            - 'Browsing, finding, viewing': 'api/public_php_api_browsing.md'
            - 'Managing Content': 'api/public_php_api_managing_content.md'
            - 'Locations': 'api/public_php_api_locations.md'
        - Field Type:
            - 'Field Type API': 'api/field_type_api.md'
            - 'Reference': 'api/field_type_reference.md'
            - 'REST API interaction': 'api/field_type_REST.md'
            - 'Public API interaction': 'api/field_type_public.md'
            - 'Schema': 'api/field_type_setting_schema.md'
            - 'Template': 'api/field_type_template.md'
            - 'Registration': 'api/field_type_registration.md'
            - 'Testing': 'api/field_type_testing.md'
            - 'Storage': 'api/field_type_storage.md'
            - 'Search': 'api/field_type_search.md'
    - Guide:
        - Introduction:
            - 'Architecture': 'guide/architecture.md'
            - 'Bundles': 'guide/bundles.md'
        - 'Content model': 'guide/content_model.md'
        - 'Configuration': 'guide/configuration.md'
        - Content rendering:
            - 'Content rendering': 'guide/content_rendering.md'
            - 'Controllers': 'guide/controllers.md'
            - 'Templates': 'guide/templates.md'
            - 'Landing Page rendering': 'guide/landing_page_rendering.md'
            - 'Twig functions reference': 'guide/twig_functions_reference.md'
        - Content management:
            - 'Images': 'guide/images.md'
            - 'File management': 'guide/file_management.md'
            - 'User-generated content': 'guide/user_generated_content.md'
        - Permissions:
            - 'Permissions': 'guide/permissions.md'
            - 'Limitations': 'guide/limitations.md'
            - 'Custom Policies': 'guide/custom_policies.md'
        - Search:
            - 'Search': 'guide/search.md'
            - 'Solr search engine': 'guide/solr.md'
            - 'Other search engines': 'guide/search_engines.md'
        - Multisite:
            - 'Multisite': 'guide/multisite.md'
            - 'SiteAccess': 'guide/siteaccess.md'
            - 'Internationalization': 'guide/internationalization.md'
        - Repository:
            - 'Repository': 'guide/repository.md'
            - 'SignalSlots': 'guide/signalslots.md'
        - Cache:
            - 'HTTP cache': 'guide/http_cache.md'
            - 'Persistence cache': 'guide/persistence_cache.md'
        - 'Clustering': 'guide/clustering.md'
        - DevOps:
            - 'DevOps': 'guide/devops.md'
            - 'Performance': 'guide/performance.md'
            - 'Environments': 'guide/environments.md'
            - 'Sessions': 'guide/sessions.md'
            - 'Security': 'guide/security.md'
        - Extending eZ Platform:
            - 'Extending eZ Platform': 'guide/extending_ez_platform.md'
            - 'Extending the Dashboard': 'guide/dashboard.md'
            - 'Other extensibility': 'guide/other_extensibility.md'
        - 'Service container': 'guide/service_container.md'
        - 'Personalization': 'guide/personalization.md'
        - 'Best practices': 'guide/best_practices.md'
    - Cookbook:
        - 'Authenticating a user with multiple user providers': 'cookbook/authenticating_a_user_with_multiple_user_providers.md'
        - 'Converting request paremeters into API objects': 'cookbook/converting_request_parameters_into_api_objects.md'
        - 'Creating content with binary attachments via REST API': 'cookbook/creating_content_with_binary_attachments_via_rest_api.md'
        - 'Creating custom notification for Flex Workflow': 'cookbook/creating_custom_notifications_for_flex_workflow.md'
        - 'Displaying children of a Content item': 'cookbook/displaying_children_of_a_content_item.md'
        - 'Displaying content with simple templates': 'cookbook/displaying_content_with_simple_templates.md'
        - 'Executing long-running console commands': 'cookbook/executing_long_running_console_commands.md'
        - 'Exposing Siteaccess-aware configuration for your bundle': 'cookbook/exposing_siteaccess_aware_configuration_for_your_bundle.md'
        - 'Importing settings from a bundle': 'cookbook/importing_settings_from_a_bundle.md'
        - 'Injecting parameters in content views': 'cookbook/injecting_parameters_in_content_views.md'
        - 'Listening to core events': 'cookbook/listening_to_core_events.md'
        - 'Making cross-origin HTTP requests': 'cookbook/making_cross_origin_http_requests.md'
        - 'Paginating API search results': 'cookbook/paginating_api_search_results.md'
        - 'Retrieving root Location': 'cookbook/retrieving_root_location.md'
        - 'Setting up Amazon AWS S3 clustering': 'cookbook/setting_up_amazon_aws_s3_clustering.md'
        - 'Setting up multi-language SiteAccesses and corresponding translations': 'cookbook/setting_up_multi_language_siteaccesses.md'
        - 'Using RouteReference': 'cookbook/using_routereference.md'
    - Resources and community:
        - 'Resources': 'community_resources/resources.md'
        - 'Professional training services': 'community_resources/professional_training_services.md'
        - 'Contributing': 'community_resources/contributing.md'
    - Migrating to eZ Platform:
        - 'Migrating from eZ Publish Platform': 'migrating/migrating_from_ez_publish_platform.md'
        - 'Migrating from eZ Publish': 'migrating/migrating_from_ez_publish.md'
    - Releases:
        - 'Updating eZ Platform': 'releases/updating_ez_platform.md'
        - 'eZ Platform v2.1.0': 'releases/ez_platform_v2.1.0.md'
        - 'eZ Platform v2.0.0': 'releases/ez_platform_v2.0.0.md'
        - 'eZ Platform v1.13.0 LTS': 'releases/ez_platform_v1.13.0_lts.md'
        - 'eZ Platform v1.12.0': 'releases/ez_platform_v1.12.0.md'
        - 'eZ Platform v1.11.0': 'releases/ez_platform_v1.11.0.md'
        - 'eZ Platform v1.10.0': 'releases/ez_platform_v1.10.0.md'
        - 'eZ Platform v1.9.0': 'releases/ez_platform_v1.9.0.md'
        - 'eZ Platform v1.8.0': 'releases/ez_platform_v1.8.0.md'
        - 'eZ Platform v1.7.0 LTS': 'releases/ez_platform_v1.7.0_lts.md'
        - 'eZ Platform v1.6.0': 'releases/ez_platform_and_ez_enterprise_v1.6.0.md'
        - eZ Enterprise release notes:
            - 'eZ Enterprise v1.5.0': 'releases/ez_enterprise_v1.5.0_release_notes.md'
            - 'eZ Enterprise v1.4.0': 'releases/ez_enterprise_v1.4_release_notes.md'
            - 'eZ Studio 2016.04': 'releases/ez_studio_2016.04_release_notes.md'
            - 'eZ Studio 16.02': 'releases/ez_studio_16.02_release_notes.md'
            - 'eZ Studio 15.12.1': 'releases/ez_studio_15.12.1_release_notes.md'
            - 'eZ Studio 15.12': 'releases/ez_studio_15.12_release_notes.md'
        - eZ Platform release notes:
            - 'eZ Platform v1.5.1': 'releases/ez_platform_1.5.1_release_notes.md'
            - 'eZ Platform v1.5.0': 'releases/ez_platform_v1.5.0_release_notes.md'
            - 'eZ Platform v1.4.2': 'releases/ez_platform_1.4.2_release_notes.md'
            - 'eZ Platform v1.4.0': 'releases/ez_platform_v1.4.0_release_notes.md'
            - 'eZ Platform 2016.04': 'releases/ez_platform_2016.04_release_notes.md'
            - 'eZ Platform 16.02': 'releases/ez_platform_16.02_release_notes.md'
            - 'eZ Platform 15.12.1': 'releases/ez_platform_15.12.1_release_notes.md'
            - 'eZ Platform 15.12': 'releases/ez_platform_15.12_release_notes.md'
            - 'Earlier releases': 'releases/earlier_releases.md'
    - 'References': 'references.md'
theme:
  name: null
  custom_dir: 'material'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
      primary: 'blue grey'
      accent: 'deep orange'

  font: false
  logo: 'images/eZ-Brandmark.png'
  feature:
      tabs: false
  search_index_only: false

theme_dir: material

extra_css: [fonts/MavenPro.css, css/custom.css, '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css']
extra_javascript: [js/jquery.min.js, js/custom.js, '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js']
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
