ibexa_design_engine:
    design_list:
        my_design: [ my_theme ]

ibexa:
    system:
        site_group:
            design: my_design
            content_view:
                full:
                    editor_articles:
                        template: '@ibexadesign/full/featured_article.html.twig'
                        match:
                            Identifier\ContentType: article
                            #\App\View\Matcher\Owner: [johndoe, janedoe]
                            App\Owner: [johndoe, janedoe]
