ibexa_taxonomy:
    taxonomies:
        tags:
            parent_location_remote_id: taxonomy_tags_folder
            content_type: tag
            field_mappings:
                identifier: identifier
                parent: parent
                name: name
        content_categories:
            parent_location_remote_id: <content_categories_remote_id>
            content_type: content_category
            field_mappings:
                identifier: category_identifier
                parent: parent_category
                name: name
            assigned_content_tab: false
            register_main_menu: false
