ibexa_design_engine:
    design_list:
        my_design: [my_theme, eshop_base_theme, eshop_ui_base_theme, transaction_theme, checkout_base_theme]
    templates_theme_paths:
        eshop_base_theme:
            - '%kernel.project_dir%/vendor/ibexa/commerce-shop/src/bundle/Eshop/Resources/views'
        eshop_ui_base_theme:
            - '%kernel.project_dir%/vendor/ibexa/commerce-shop-ui/src/bundle/Resources/views/themes/standard'
        checkout_base_theme:
            - '%kernel.project_dir%/vendor/ibexa/commerce-checkout/src/bundle/Resources/views/themes/standard/'
        transaction_theme:
            - '%kernel.project_dir%/vendor/ibexa/commerce-transaction/src/bundle/ShopFrontend/Resources/views/themes/standard/'

ibexa:
    system:
        site:
            design: my_design
            content_view:
                embed:
                    product_card:
                        template: '@ibexadesign/embed/product_card.html.twig'
                        match:
                            Identifier\ContentType: 'ses_product'
